/* Generated By:JavaCC: Do not edit this line. CSParserConstants.java */
package aTSE;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CSParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOE = 5;
  /** RegularExpression Id. */
  int EQUALS = 6;
  /** RegularExpression Id. */
  int SITESEP = 7;
  /** RegularExpression Id. */
  int ITEMSEP = 8;
  /** RegularExpression Id. */
  int TOKENSEP = 9;
  /** RegularExpression Id. */
  int AFTER = 10;
  /** RegularExpression Id. */
  int BEFORE = 11;
  /** RegularExpression Id. */
  int BETWEEN = 12;
  /** RegularExpression Id. */
  int STRING = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\";\"",
    "\"=\"",
    "\"->\"",
    "\":\"",
    "\".\"",
    "\"after\"",
    "\"before\"",
    "\"between\"",
    "<STRING>",
  };

}
